### ISSUE TITLE
how to clear selection on non-file clicks ?

### ISSUE THREAD

**Issue by navidsedighpour** [TimboKZ/Chonky#100]

**Comment by navidsedighpour** [comment]
As you see in the picture i need to clear selection on click of the non-file area.

![image](https://user-images.githubusercontent.com/15349679/126947841-af13c3b9-2427-41f5-a380-309aac64ad6e.png)

**Comment by TimboKZ** [comment]
There is no built-in feature for this right now. You can implement some custom `onClick` logic that would detect clicks that are inside the `FileBrowser` component but outside of `FileEntry` components, and then dispatch an action to clear file selection.
