### ISSUE TITLE
Preview DXF (Catia) files

### ISSUE THREAD

**Issue by esanmar** [TimboKZ/Chonky#11]
Hi,

It would be great integrate this component to view DXF files:

https://github.com/gdsestimating/three-dxf

Thanks!

**Comment by TimboKZ** [comment]
Hello, if you mean generating the thumbnail based on the DXF file, I think this feature lies outside of the scope of Chonky. Chonky can render whatever images are returned by [thumbnail generator](https://timbokz.github.io/Chonky/#section-displaying-file-thumbnails), and it is the responsibility of the library user to generate the thumbnails.

For example, if you could save the contents of the canvas into an image, you could get URL to the blob using:
```js
const blobUrl = URL.createObjectURL(blob);
```
This URL can the be returned from the thumbnail generator for Chonky to display it.
