### ISSUE TITLE
Way to disable or control keypress event listeners

### ISSUE THREAD

**Issue by fernandopabst** [TimboKZ/Chonky#118]
First of all, what an amazing library! Thank you for your work in this, just love it.

Now, for my issue: I've embedded the file browser in my app next to a text editor - but because chonky listens to some keypresses (like backspace) in order to move up the folder tree structure, I can't use backspace in my text editor as chonky keeps stealing focus.

I've had a potter around but I'm afraid I'm unable to disable these listeners. Any idea how to achieve this?

**Comment by TimboKZ** [comment]
As discussed on Discord, you can overwrite essential actions by specifying a custom action with the same action ID.
