### ISSUE TITLE
Option to specify if toolbar items should be visible

### ISSUE THREAD

**Issue by frankbolviken** [TimboKZ/Chonky#13]
Would be really usefull if it would be possible to for instance hide the "options" toolbar item. 
Is this possible at this moment and just not documented?

**Comment by TimboKZ** [comment]
Hello, at the moment this is not a supported, however it is often requested and will be added in future versions of Chonky. When these future versions will arrive is not clear at the moment.

If you need this feature urgently, I suggest you override the CSS styles for the Options container and hide it completely with `display: none`.

**Comment by TimboKZ** [comment]
Hello, FYI this feature is officially supported in the upcoming `1.x` release. You can see it in actions in the [Disabling default file actions](https://timbokz.github.io/Chonky/1.x/?path=/docs/2-file-browser-examples-disabling-default-file-actions--disable-example) section of the new docs.

**Comment by TimboKZ** [comment]
Version 1.0 is now released. This functionality is covered under file actions in 1.0.
