### ISSUE TITLE
disableDragAndDropProvider doesn't work as intended

### ISSUE THREAD

**Issue by duchuule** [TimboKZ/Chonky#158]
I'm following the guide at https://chonky.io/docs/2.x/basics/drag-n-drop to have multiple FileBrowser on the same page. However, as soon as I set to true, all drag and drop functionalities stop working even if I provide my own DndProvider. Code example here
https://codesandbox.io/s/kfxyl

Any idea on how to fix this?

**Comment by embeddedt** [comment]
I found that you must use *exactly* version 11.1.3 of `react-dnd` and the backend, as this is the version Chonky uses internally. If you use a different version, your provider is incompatible with Chonky.

Fixed example: https://codesandbox.io/s/chonky-disabledraganddropprovider-error-forked-q5zzu5

**Comment by duchuule** [comment]
Thank you. It works for me now. Perhaps the documentation could be updated to include the exact version of react-dnd to use.

**Comment by ganlvtech** [comment]
I found that I must restart Vite server and clear cache after doing `npm install react-dnd react-dnd-html5-backend`. Hot Module Replacement will cause some bug.
