### ISSUE TITLE
File action menu on list items

### ISSUE THREAD

**Issue by avivklas** [TimboKZ/Chonky#16]
Hello kind people. Love your work ❤️ 

What do you think about adding the ability to display a popup menu with all file actions near every item in the list so file actions will be close to their context in the case when the desired action is on a single file?

**Comment by TimboKZ** [comment]
That's an interesting idea. I am already planning to add support for [react-context-menu-wrapper](https://www.npmjs.com/package/react-context-menu-wrapper) to let users specify custom context menus, but also providing a default context menu implementation sounds like a great idea.

I'll keep this in mind when working on context menus, though I can't promise any release dates.

**Comment by TimboKZ** [comment]
Hi, FYI I have just added file context menus to the alpha version of Chonky 2.x. You can see the preview GIF below.

Chonky 2.x also has a much more powerful file action framework. You can play around with it here: 

https://chonky.io/storybook/2.x/?path=/story/file-browser-demos--virtual-file-system

Please keep in mind that Chonky 2.x is still in alpha and can change significantly.

![Chonky Context Menu demo](https://user-images.githubusercontent.com/5504588/97066382-ee35e600-15ac-11eb-99d6-bcec9b0d8b05.gif)

**Comment by avivklas** [comment]
This is awesome! Thanks ❤️
