### ISSUE TITLE
Chonky's buttons don't specify the `type` attribute

### ISSUE THREAD

**Issue by Keony1** [TimboKZ/Chonky#17]
So, when you are working with Chonky inside an form for any reason
any button of chonky when get clicked will trigger submit event.
This happens because none of the buttons has the attribute type="button"

**Comment by TimboKZ** [comment]
Hi, thanks for the report. This should be an easy enough fix, since most Chonky buttons use a common button component. I'll try to release a fix tonight.

Out of curiosity, how are you using Chonky inside forms?

**Comment by Keony1** [comment]
Hello @TimboKZ. Thank you for your speed in answering, this is very cool.

I have a page that is a form that has multiple tabs (sorry for my english)
each tab is one part of form, the last tab is where Chonky resides. 
to keep the layout I had to leave this tab inside the form

![image](https://user-images.githubusercontent.com/30664147/87781585-508d8680-c807-11ea-8aba-b52d4c473ff7.png)

**Comment by TimboKZ** [comment]
Hello, I just released `v1.0.6` which updates the `<button>` tags and the search input to avoid submitting the form.

Can you please verify that the problem is solved on your end?

**Comment by Keony1** [comment]
It's solved. Thanks @TimboKZ  o/
