### ISSUE TITLE
Search feature for non hooks version

### ISSUE THREAD

**Issue by shanmugarajbe** [TimboKZ/Chonky#19]
Working on implementing Chonky non hooks version to older react project. Search feature is required as per our requirement which is missing in non-hooks version. I know that latest hooks version have search feature. But is there option to add search feature to the non hooks version?

**Comment by TimboKZ** [comment]
Hi, at this point I'm reluctant to add any new features to the `0.x` version of Chonky.

If you own the project, I would recommend upgrading to a recent version of `react` and `react-dom` and using Chonky 1.x. In some cases this migration doesn't require any code changes, in other cases there are CLI tools to automate migration. See:
https://reactjs.org/blog/2017/09/26/react-v16.0.html#upgrading

If migrating is not an option, you can always implement file search yourself. As you know Chonky takes a `files` array as one of its props. You can have some external `<input type="text"/>` component accept the search string from the user, and then use it to filter your file array before passing in to Chonky. I recommend [fuzzy-search](https://www.npmjs.com/package/fuzzy-search) package for this purpose.

**Comment by shanmugarajbe** [comment]
Thanks for quick reply. 

It's not my own project and I can't update my react and react-dom. I will implement own search for the older version as suggested. 

Keep up the good work.

**Comment by TimboKZ** [comment]
Thanks, good luck with search implementation!
