### ISSUE TITLE
onMoveFiles usage

### ISSUE THREAD

**Issue by ilkermutlu** [TimboKZ/Chonky#2]
The documentation mentions `onMoveFiles`, but couldn't find any explanation on how to implement that.

How can I get the related event fired?

**Comment by TimboKZ** [comment]
I think documentation and the actual code are out of sync there.

`onMoveFiles` was supposed to be fired when the user drags & drops selected files into some folder. Since drag & drop is not supported yet, `onMoveFiles` is never fired.

Unfortunately there is no ETA for drag & drop at this time.

**Comment by Muhammadali40** [comment]
@TimboKZ  When you will provide **drag&Drop** feature. ?i need it in my project as i am using chonky file manager

**Comment by TimboKZ** [comment]
Not any time soon. 

The story there is that I wanted to implement drag & drop from the very start, but couldn't get any of the popular drag & drop libraries to work with Chonky's layout (virtualization + multiple list views). In my eyes this basically means that getting drag & drop to work will take a considerable amount of time and will probably require major changes to layout.

Sadly I don't have the time for that moment.

I have some plans to adapt hooks in Chonky, and I can look at drag & drop again as a part of that rewrite, but again, this will not happen any time soon.

**Comment by TimboKZ** [comment]
@Muhammadali40 Drag & drop features is a part of the recently released Chonky 1.0.
