### ISSUE TITLE
TypeError: Cannot read property 'SmallThumbs' of undefined

### ISSUE THREAD

**Issue by raahim-bukhari-ivolve** [TimboKZ/Chonky#20]
Whenever I am passing FileView.SmallThumbs in View, this error ocurs.

**Comment by TimboKZ** [comment]
I think you might be trying to use v0.x functionality in v1.x of Chonky. v1.x doesn't support switching between views yet.

**Comment by raahim-bukhari-ivolve** [comment]
Yes, I changed the version in the package.json file. Now working absolutely fine.
Thanks
