### ISSUE TITLE
Question - How can I get selected file list outside Chonky?

### ISSUE THREAD

**Issue by tomeraz** [TimboKZ/Chonky#21]
Hi,

Handling a use case where I have to know which files are chosen, outside chonky.
Is there a callback, hook or another way that I can use to know which files are chosen, without calling a file action?
Is it possible to dispatch an event to chonky programatically using Javascript, without having the buttons appear in the toolbar?

**Comment by TimboKZ** [comment]
Hi, getting selections programmatically was a feature in v0.x, but it was not ported to v1.x yet.

Dispatching events programmatically, without adding buttons or actions, is not supported yet.

I am planning to work on both of these features (and some others) over the span of the next few weeks.

**Comment by tomeraz** [comment]
Thank you 🙏
We can use this to solve our problem. However we downgraded to 0.2.4 and it's doing the job we need well.
