### ISSUE TITLE
Possibility to add translation files

### ISSUE THREAD

**Issue by NSerlonghi** [TimboKZ/Chonky#22]
Hi,
have you already foreseen a way to set other languages by inserting translation files? If not, will there be in the future? In my opinion, it would be very useful. Thanks for your work!

**Comment by TimboKZ** [comment]
Hello! Text localisation is not currently supported.

At the same time, the only hardcoded English string in Chonky is "Nothing to show" banner that you see when the folder is empty. Take a look at #15 to see how this string can be translated.

As for the other strings - they come from the `ChonkyActions` object and default actions. You can easily overwrite the names using any language you want (though it is a bit tedious).

With the above in mind, I don't have any immediate plans to support localisation. If Chonky will require more hardcoded strings in the future, I'll consider adding localisation support.
