### ISSUE TITLE
ChangeSelection action dispatched when clicking outside of file browser

### ISSUE THREAD

**Issue by sleiss** [TimboKZ/Chonky#26]
Hey, I'm trying to implement a button that, once clicked, processes the currently selected files.

I however face the following issue:
Once I click on the button to submit (which is not part of the file browser but of a parent component), the `ChangeSelection` action is triggered with no selected files.
Now, once the logic of the button is executed, the selected files are empty.

Is there a possibility to prevent the `ChangeSelection` action to be triggered when clicking outside of the FileBrowser?

Thanks!

**Comment by TimboKZ** [comment]
Hello, there is no explicit option to disable that logic currently, but I should probably add one.

That said, Chonky includes the logic to *not* clear out the selection when the outside click is on a button. I am surprised it does not kick in in your case. See source code below:
https://github.com/TimboKZ/Chonky/blob/eb0d5ec08d2d25a0800763b99a013a11793badc4/src/util/hooks-helpers.ts#L62-L68

Can you share a minimal example/reproduction of your problem? I'm curious to see what tags/components you are using.

**Comment by sleiss** [comment]
@TimboKZ Thanks again for your fast reply.

I just tested it and indeed, Chonky is checking if a button is clicked.
The problem seems to arise as I use the `Button` component from Material UI (https://material-ui.com/components/buttons/).

When I inspect the button from the material UI documentation, I get the following:
![image](https://user-images.githubusercontent.com/5084100/92727333-3d161c00-f36f-11ea-9bc8-baada469197c.png)

The label (which contains the text displayed in the button) is displayed using `<span>`, so if I click the edge of the button, it is actually working fine (as I click on the button, Chonky registers that and prevents clearing the selection).
If I however click on the middle of the button (where the label and hence the `<span>` is), the selection gets cleared as the code you mentioned above does not trigger.

So your code is working as expected, but it seems that there are some edge-cases that could be handled better.
 
One solution that came into my mind: Chonky could check if any of the parent elements of the target is a `button` (and not only the target itself).
Would that be a solution that seems rational?

**Comment by sleiss** [comment]
I've drafted a PR that might resolve the issue: https://github.com/TimboKZ/Chonky/pull/27.
It is **untested**, but maybe you can have a look at it.

**Comment by TimboKZ** [comment]
The PR looks good to me, will try to merge it later today.

**Comment by sleiss** [comment]
@TimboKZ Have you had a chance to check the PR?

**Comment by TimboKZ** [comment]
Hi, yes I have, but didn't have the time to merge it yet. 

Apologies for the delay, I'll try to deal with it be the end of this week.

**Comment by TimboKZ** [comment]
I have just released [Chonky v1.1.2](https://github.com/TimboKZ/Chonky/releases/tag/v1.1.2), that includes the PR you raised and also a new `FileBrowser` prop called `clearSelectionOnOutsideClick`. This new prop can be used to prevent the file selection from being cleared when users clicks outside of the file browser container.

**Comment by sleiss** [comment]
Thanks for your work!
The new prop works as expected!
