### ISSUE TITLE
How can I remove/customize icons for image files? 

### ISSUE THREAD

**Issue by Sultan-Mohammad** [TimboKZ/Chonky#29]

**Comment by TimboKZ** [comment]
Hi, all of the icons are defined in this file: https://github.com/TimboKZ/Chonky/blob/1.x/src/util/file-icon-helper.ts

There is no mechanism to customise this logic yet, although I think it would be pretty easy to implement. Unfortunately my backlog of features for Chonky is full with other things, so I'm not sure if I'll be able to work on this any time soon.

There is a feature coming (https://github.com/TimboKZ/Chonky/issues/5) that would let you customize the icon graphics, but not the extension -> icon mapping. I'm not sure if that helps.

**Comment by TimboKZ** [comment]
Can you give me some more information about your use case? Perhaps there is some other way to achieve this.

**Comment by Sultan-Mohammad** [comment]
![chonky file icons](https://user-images.githubusercontent.com/12228561/94796688-ec8b5f00-0400-11eb-9b1c-949c1f101eaf.png)

As you can see in the screenshot, I've added the thumbnails for my image files, now I want to remove the file icon on the foreground, How can I achieve that?

**Comment by TimboKZ** [comment]
Thanks for the info. This looks like a pretty important use case to me, so I'll prioritize relevant changes to complete them sooner.

Unfortunately, at the moment there is no easy way to disable these icons. However, after some small changes to Chonky source code, it should be easy to achieve. I can change `entryClassName` in the file below to include a class like `chonky-has-thumbnail`.

https://github.com/TimboKZ/Chonky/blob/1.x/src/components/file-entry/FileEntryGrid.tsx#L30

Once this is done, you can add a short CSS snippet to your project to hide icons in all file entries that have custom thumbnails:
```css
.chonky-file-entry.chonky-has-thumbnail .chonky-file-icon {
    display: none;
}
```

I'll try to make this change ASAP.

**Comment by Sultan-Mohammad** [comment]
Thanks, I'll try your suggestion on my project. Hope we can get this enhancement ASAP

**Comment by TimboKZ** [comment]
Hi, I have just released [Chonky v1.1.3](https://github.com/TimboKZ/Chonky/releases/tag/v1.1.3), that adds `chonky-file-entry-has-thumbnail` class to file entries with thumbnails. You can now use the following CSS to hide icons for such file entries:
```css
.chonky-file-entry-has-thumbnail .chonky-file-icon {
    display: none !important;
}
```

**Comment by Sultan-Mohammad** [comment]
Thanks, It works now

**Comment by mukeshrao-cesit** [comment]
import { setChonkyDefaults } from 'chonky';
import { ChonkyIconFA } from 'chonky-icon-fontawesome';
import { FullFileBrowser, ChonkyActions, ChonkyIconProps } from 'chonky';
import { useEffect, useState } from 'react';
import data from './data';
import folderSearch from './FolderSearch';
import handleAction from './ActionHandler';
import { customActions } from './CustomAction';
import { ReactComponent as FolderIcon } from '../../assets/img/folder.svg';
import React from 'react';

const FolderPage = () => {
	const handleActionWrapper = (data) => {
		handleAction(data, setCurrentFolder);
	};
	setChonkyDefaults({ iconComponent: ChonkyIconFA });

	const [currentFolder, setCurrentFolder] = useState('0');
	const [files, setFiles] = useState(null);
	const [folderChain, setFolderChain] = useState(null);
	const fileActions = [...customActions, ChonkyActions.DownloadFiles];

	const myIconMap = {
		folder: FolderIcon,
	};
	const MyIcon = React.memo((props) => {
		console.log(props);
		const IconComponent = myIconMap[props.icon];
		if (IconComponent && props.isDir) {
			return <IconComponent />;
		}
		return <ChonkyIconFA {...props} />;
	});

	useEffect(() => {
		let folderChainTemp = [];
		let filesTemp = [];

		const [found, filesTemp1, folderChainTemp1] = folderSearch(data, folderChainTemp, currentFolder);
		if (found) {
			filesTemp = filesTemp1;
			folderChainTemp = folderChainTemp1;
		}
		setFolderChain(folderChainTemp);
		setFiles(filesTemp);
	}, [currentFolder]);

	return (
		<div className="App">
			<FullFileBrowser
				iconComponent={MyIcon}
				files={files}
				folderChain={folderChain}
				defaultFileViewActionId={ChonkyActions.EnableListView.id}
				fileActions={fileActions}
				onFileAction={handleActionWrapper}
				disableDefaultFileActions={true}
			/>
		</div>
	);
};

export default FolderPage;


I have a issue like then icon is loading for list view nut it's not loading for grid view. Here is my code, Can someone help me in this?
