### ISSUE TITLE
Update to React 16.13 and Recoil 0.0.13

### ISSUE THREAD

**Issue by yacinebenkaidali** [TimboKZ/Chonky#30]
Cannot update a component (`Batcher`) while rendering a different component (`ForwardRef`). To locate the bad setState() call inside `ForwardRef`

**Comment by TimboKZ** [comment]
Hi, this is a known problem. It goes away once you update React to `16.13` and Recoil to `0.0.13`. I'm planning to release an update making this change over the next few days.

**Comment by yacinebenkaidali** [comment]
Hi, Thanks in advance 
can you notify me once you're done ?
you're components is amazing <3

**Comment by TimboKZ** [comment]
Sure, I'll post an update on this ticket once this is done.

**Comment by TimboKZ** [comment]
Hi, I have just released Chonky v1.1.4 that updates package versions.
