### ISSUE TITLE
File names get clipped in description section

### ISSUE THREAD

**Issue by Sultan-Mohammad** [TimboKZ/Chonky#32]
Hi, My file names are getting clipped in the description section, even for a small name(e.g. 6 characters length)

![image](https://user-images.githubusercontent.com/12228561/95317942-ac702480-08b7-11eb-98ec-5dff42e5240e.png)
![image](https://user-images.githubusercontent.com/12228561/95318048-cf9ad400-08b7-11eb-9682-efba3a89bfd7.png)

**Comment by Sultan-Mohammad** [comment]
Maybe the library tried to clip the file extension. Instead, it's clipping characters from the oiginal file name with the same length as the extension.

**Comment by TimboKZ** [comment]
Hi, this is expected behaviour. Please see the end of *The FileData Type* section in [relevant docs](https://timbokz.github.io/Chonky/1.x/?path=/docs/basics-displaying-files--files-array-example).

**Comment by Sultan-Mohammad** [comment]
Thanks, got it
