### ISSUE TITLE
Files and folder renaming

### ISSUE THREAD

**Issue by AndreyVanyakin** [TimboKZ/Chonky#36]
Hi Timbo,

Thank you again for such a great library.

Is there any recommended way to handle file/folder renames? 
Is there a way out of the box to have an input field where the filename is after a particular action is triggered?
![image](https://user-images.githubusercontent.com/38654357/97113946-99a28000-16fe-11eb-99b1-b42272e381b5.png)

Cheers,
Andrey

**Comment by TimboKZ** [comment]
Hi, thanks.

Chonky doesn't have any built-in logic for showing dialogs/forms when an action is activated.

That said, Chonky 2.x uses [Material UI](https://material-ui.com/) under the hood, which has very "Chonky-like" look & feel out of the box. I highly recommend their [Dialog component](https://material-ui.com/components/dialogs/#form-dialogs), which supports forms. Of course MUI Dialog will work just as well with Chonky 1.x.

To see how renaming dialog could be implemented, check out the `ChonkyActions.CreateFolder` handler here: https://chonky.io/storybook/2.x/?path=/story/file-browser-demos--mutable-virtual-file-system
