### ISSUE TITLE
Support Nested JSON filesystem

### ISSUE THREAD

**Issue by deranjer** [TimboKZ/Chonky#4]
I don't know if this would be simple or not, but was curious if you would be able to implement a nested JSON filesystem input, I find that approach to be much easier to implement on the backend.

**Comment by TimboKZ** [comment]
I think the current logic nicely abstracts away the FS-specific logic.

For my personal use cases, my backend also serves the data in a nested fashion. This data is then normalised to remove nesting and written to Redux store.

The data Chonky displays is then picked up from the Redux store.

Would that approach work for you?

**Comment by deranjer** [comment]
It is fine, yes, I did solve it in the backend, I had been testing the DevExpress file manager (it is very nice, but is not released yet and does not have all the features I require yet) which accepted it in a nested form: https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileManager/BindingToHierarchicalStructure/React/Light/

I was hoping to re-use that but Chonky would not accept that format.  I flattened it but realized I had an ID issue since I was just using the folder name for the ID before (in DevExpress) and since it was nested it was no problem. I was already generating ULID's for all my documents so had to do that for my folders as well so I wouldn't have a name collision since it is very possible (in fact very likely) my users will have duplicate folder names.

Everything is working fine so far, I have the basic filesystem running and can display files.  I'm not great with react, so I did find this hard to understand:

```
if (folder) {
            let currentFolder = folder;
            while (currentFolder) {
                folderChain.unshift(currentFolder);
                const parentId = currentFolder.parentId;
                currentFolder = parentId ? this.fileMap[parentId] : null;
            }
            if (folder.childrenIds) {
                files = folder.childrenIds.map(id => this.fileMap[id]);
            }
        }
```
I implemented it this way instead, and it appears to work: 
```
if (file.isDir) {
            let tempFile = file
            let folderTreeNew = [file] //add the current folder to the array
            let inFolder = file
            while (inFolder.parentID != "") {
                fullFileTree.find(function(currentFile, index) {
                    if (currentFile.id == tempFile.parentID) {
                        inFolder = currentFile
                        folderTreeNew.unshift(currentFile)
                        tempFile = currentFile
                    }
                })
            }
            setFolderSystem(folderTreeNew)
            getFiles(file, fullFileTree)

```

The only other thing I would love this to have is a filetree view on the left hand side (that is collapsible).  Otherwise, really loving the library.
