### ISSUE TITLE
Chonky 1.1.6 release issues

### ISSUE THREAD

**Issue by AndreyVanyakin** [TimboKZ/Chonky#41]
Hi, 

Something seems to be wrong with the current 1.x release (or perhaps previous ones too).
I tried to update to v1.1.6. I'm using yarn

Getting this error 
![image](https://user-images.githubusercontent.com/38654357/97574225-f4d4bb00-19fb-11eb-8e20-14675235800e.png)

This is folder in node_modules
![image](https://user-images.githubusercontent.com/38654357/97574131-d5d62900-19fb-11eb-827b-80d4dbe442ff.png)

Checked in another project (installed Chonky there). Same thing.

Cheers, Andrey

**Comment by TimboKZ** [comment]
Hi Andrey,

Thanks for reporting this, I know exactly what the issue is - the build folder is not present in the release. 

Will fix in the evening. Meanwhile please use 1.1.5.

Tim

**Comment by TimboKZ** [comment]
Hi, Chonky should be working again in v1.1.7 release. Can you please verify?
