### ISSUE TITLE
Ctrl -> Cmd for MacOS

### ISSUE THREAD

**Issue by TheAksh** [TimboKZ/Chonky#48]
There's no facility to select multiple files for Mac users at the moment. Cmd key isn't mapped and Ctrl+click triggers the option menu.
Needs a mapping change, perhaps.

**Comment by TheAksh** [comment]
Helping you by giving a starting point 😇

https://stackoverflow.com/questions/3902635/how-does-one-capture-a-macs-command-key-via-javascript

**Comment by TheAksh** [comment]
Actually, on second thoughts, instead of mapping it to Cmd key, a better idea would be detect Ctrl+Click in Mac override the functionality explicitly.

**Comment by TimboKZ** [comment]
I was under the impression that this was a built-in feature in `hotkey-js`, but I guess not. Will make the fix.
