### ISSUE TITLE
react-scripts fails with Node version 10 or version 12

### ISSUE THREAD

**Issue by TheAksh** [TimboKZ/Chonky#49]
Unfortunately we can't use a higher Node Version since the images on the AWS codepipeline come with those 10 and 12 versions only. https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

When chonky, chonky-icon-fontawesome and path are added to package.json, running react-scripts command fails.

Can chonky and chonky-icon-fontawesome be configured to support Node versions 10 and 12 too?

**Comment by TimboKZ** [comment]
Hello, what error does react-scripts fail with?

**Comment by TheAksh** [comment]
Please ignore this issue. Delete it as well if possible. The cause was something else, but the effects were only showing up once I remove Chonky packages. Hence, thought Chonky was the reason.
