### ISSUE TITLE
Context menu doesn't show clicked file when disableSelection is enabled

### ISSUE THREAD

**Issue by bilicio** [TimboKZ/Chonky#56]
I disabled the file selection to only enable one file selected at a time, but when i do that the context menu cant get the file selected.  the variable "set" from selected came empty. even when i use ref with getFileSelection.

**Comment by TimboKZ** [comment]
File selection will always be empty when `disableSelection` is set to `true`, so that part is working as expected.

You can get the file that activated the context menu using `data.state.contextMenuTriggerFile` (in your action handler). Note that this field can be undefined if user opened the context menu by right clicking on empty space.

**Comment by bilicio** [comment]
Hi Tim! thank you! 
i tried use `data.state.contextMenuTriggerFile` but came null every time, even if the file is selected before right click.

**Comment by TimboKZ** [comment]
Hi, I just tested the relevant logic with this example:
https://codesandbox.io/s/chonky-issue-56-3nl6s?file=/src/App.js

Chonky is working as expected. Please update to the most recent version of Chonky and see if it helps.

**Comment by bilicio** [comment]
I got it tim! thank you, i tried to get the  `data.state.contextMenuTriggerFile` before click the context menu, i can only get the file after click the option. thats ok!

One more question , i tried to use` i18n={{locales: ['pt']}}` with my location , in case Brazil, but nothing gets translated. i m using the tip from i18n site. is this the right way to use? 

by the way, merry christmas! 😄

**Comment by bilicio** [comment]
Nevermind, i went to this [example](https://github.com/TimboKZ/chonky-website/blob/master/2.x_storybook/src/demos/LocalizedVFS.tsx) and figure it out! thank you! 👍
