### ISSUE TITLE
Question about applicability

### ISSUE THREAD

**Issue by alex-treebeard** [TimboKZ/Chonky#57]
Hey there,

I'm working on a disk space analyser similar to the screenshot below. Chonky looks like it could be a good fit for the file viewer on the left.

I have a couple Q's before I jump in if that's ok:

1. How many files have you tested this library with at once? Whilst I only need to show About 50 at a time, I expect some cases where 100,000 or 1 million rows are in memory.
2. Does this library support the expand button (triangle on left of row in screen), letting you look at subdirectories without clicking through?

The closest alternative I can see is [react-virtualised-tree](https://github.com/diogofcunha/react-virtualized-tree/) Which I believe has both of the above, but requires more UI work.

Thanks!

![Screenshot 2020-12-24 at 11 08 48](https://user-images.githubusercontent.com/57841277/103085028-6aae6a80-45d8-11eb-937b-e44145ef5dcb.png)

**Comment by TimboKZ** [comment]
Hi @alex-treebeard,

1. This library uses virtualisation to deal with large file collections, so it shouldn't have any problems displaying millions of files.
2. Tree view is not currently supported, and is likely not coming soon.
