### ISSUE TITLE
Custom action button enable logic

### ISSUE THREAD

**Issue by EthanLowenthal** [TimboKZ/Chonky#59]
It would be nice to be able to disable the action buttons with custom logic, like if data is still loading or a user don't have the right permissions. Maybe put a boolean disabled prop on the FileActionButton? Another option would be to just pass all unused props down the the button itself so you could set your own IDs, disable the ripple effect, or pass the disabled prop and other props that currently aren't settable by the end programmer.

**Comment by maqsood1ahmed** [comment]
Hi @TimboKZ Thanks for providing a Great library.

I am trying to set file sort order programmatically and checked  [Actions effects](https://chonky.io/docs/2.x/file-actions/effects/#example-action-effect) but I think that's not what I need. 

Can you please suggest a way to call chonky action from my own app button?

**Comment by maqsood1ahmed** [comment]
Hi @TimboKZ can you please reply whether currently this type of feature available or not?
Thanks

**Comment by EthanLowenthal** [comment]
@maqsood1ahmed you have to use the `useChonkyStore` hook to get the store then use `store.dispatch` to dispatch your action. `useChonkyStore`  is exported from `src/redux/store.ts`. Actions are defined in the files in `src/types/...`. Check https://react-redux.js.org/ for more info on redux. Also there's a discord where Tim responds pretty quickly. I think its linked on the website.

**Comment by maqsood1ahmed** [comment]
Hi @EthanLowenthal Thanks. I just tried this technique like this way 
```   
import { useChonkyStore } from 'chonky/lib/redux/store';
import { reduxActions } from "chonky/lib/redux/reducers.js";
import { SortOrder } from 'chonky/lib/types/sort.types';

const chonkyRedux = useChonkyStore();

chonkyStore.dispatch(reduxActions.setSort({ 
                                            actionId: ChonkyActions.SortFilesByName,
                                            order: SortOrder.DESC 
                                          }))
```
though it changed the sort order but it's clearing enitre redux state. 
![image](https://user-images.githubusercontent.com/25984170/113414409-5e575c00-93d6-11eb-8208-7980f1dea2f3.png)

**Comment by mariasumedre-3pg** [comment]
PR https://github.com/TimboKZ/Chonky/pull/107 should implement this, it introduces `optionVisibility` for `FileAction`, and the custom visibility states: `Default`, `Disabled`, `Active`, `Hidden`.
An example of setting option visibility is in `MutableFS.js` storybook.

**Comment by TimboKZ** [comment]
Closing this issue as #107 was merged & released a while back, feel free to reopen if needed.
