### ISSUE TITLE
how to display files inside folder?

### ISSUE THREAD

**Issue by StarStuff15** [TimboKZ/Chonky#62]
how to set folder structure in chunky?.

**Comment by satyajitghana** [comment]
you need to use the `thumbnailUrl` in the fileMap for that, example
```javascript
            newFileMap.fileMap[file.uid] = {
                id: file.uid,
                name: file.name,
                size: file.size,
                modDate: file.lastModifiedDate,
                thumbnailUrl: URL.createObjectURL(file),
                parentId: btoa(folderName),
            };
```

**Comment by StarStuff15** [comment]
my file structure is

 cFiles: [
        { id: "lhs", name: "Home", isDir: true },
        {
          id: "mcd",
          name: "chonky-sphere-v2.png",
          thumbnailUrl: "https://chonky.io/chonky-sphere-v2.png",
          parentId: 'Home',
          childrenIds: [],
        },
      ],

**Comment by faulkie** [comment]
Did you get an answer? I'm having the same issue :

     const files = [
      {
        id: 'bnm',
        name: 'home',
        isDir: true,
        childrenIds: [ 'nTe', 'nTe2' ],
        childrenCount: 2
      },
      {
        id: 'nTe',
        name: 'Normal file.yml',
        size: 890,
        modDate: new Date('2012-01-01'),
        parentId: 'bnm',
        thumbnailUrl: "https://chonky.io/chonky-sphere-v2.png"
      },
      {
        id: 'nTe2',
        name: 'Normal file 2.yml',
        size: 890,
        modDate: new Date('2012-01-01'),
        parentId: 'bnm',
        thumbnailUrl: "https://chonky.io/chonky-sphere-v2.png"
      }
    ];

cant seem to navigate into a folder.

**Comment by TimboKZ** [comment]
Hi, please refer to the documentation and storybook examples.

**Comment by shujathaliirfan** [comment]
I'm also facing the same issue as mentioned above.(unable to navigate into folder files)
please guide us through .....
