### ISSUE TITLE
Document is not clear anyway. Have to give up.

### ISSUE THREAD

**Issue by hyc3z** [TimboKZ/Chonky#64]
1. FileData format is so messed up.
    Why not stick to nested json format? It is so much better at working with existing libs like directory-tree, and much more intuitive.
List objects with parents and children are so time-consuming to generate, and if the fs contains a lot of files, it impacts server performance. 

2. Folders are not executable .
   On your storybook website, the folders are able to be opened. However, when using the exported FullFileBrowser, they're not executable. There're issues already mentioning this problem.

3. Custom Menu Context.
  Not able to implement.

Anyway, the UI is really good, but for issues above I have to abort using this library.

**Comment by TimboKZ** [comment]
Hi, points (1) and (2) that you raised are the result of you misunderstanding the point of this library, please re-read the [philosophy section in documentation](https://chonky.io/docs/2.x/#philosophy-behind-chonky). 

As for point (3), the documentation covers how you can provide custom implementation of a context menu, and also how you add custom buttons to the context menu.
