### ISSUE TITLE
Change the default thumbnail of the folder

### ISSUE THREAD

**Issue by theumairriaz** [TimboKZ/Chonky#65]
Is there any way to change the default thumbnail of the folder in chonky v2.0?

**Comment by TimboKZ** [comment]
It is possible to change the image and the icon out of the box. With some CSS override you might be able to change some other parts of it as well.

**Comment by theumairriaz** [comment]
I will write the code and then post a comment here and then I will close it.

**Comment by theumairriaz** [comment]
```
.chonky-fileEntryClickableWrapper > * > * {
  background-color: transparent !important;
}
```
