### ISSUE TITLE
I want to show different context menu for directory and file

### ISSUE THREAD

**Issue by theumairriaz** [TimboKZ/Chonky#66]
How can I want to show the different context menu for directory and file

**Comment by TimboKZ** [comment]
Hi, sadly this is not possible at the moment. The best you can do is disable file/folder actions using `fileFilter` (assuming you have not disabled selection).

**Comment by theumairriaz** [comment]
I have implemented it by adding fileFilter for `isDir` and then adding 
`.Mui-disabled {
  display: none !important;
}` to the stylesheet.
