### ISSUE TITLE
Remove memoizee dependency

### ISSUE THREAD

**Issue by benmerckx** [TimboKZ/Chonky#67]
A suggestion: remove the memoizee dependency:

- It's used once without arguments and could be replaced by making iconTrie constant

https://github.com/TimboKZ/Chonky/blob/6b10463a16a524a629258ffca37a7f784cb9fd66/packages/chonky/src/util/icon-helper.ts#L20

- It adds [8.2kB](https://bundlephobia.com/result?p=memoizee@0.4.15) to the bundle 
- It makes bundling chonky harder [vitejs/vite#1976](https://github.com/vitejs/vite/issues/1976)

**Comment by TimboKZ** [comment]
Sounds reasonable, if you want to raise a PR making this change I'll be happy to merge it, otherwise I will get to this on the weekend.

**Comment by TimboKZ** [comment]
Hey, thanks for raising the PR. Can you try building your project with `chonky@canary` and `chonky-icon-fontawesome@canary` and see if it solves your build issues?

**Comment by TimboKZ** [comment]
Fixed in https://github.com/TimboKZ/Chonky/commit/bab607704d7a3f209502dbe35530832916de8105.
