### ISSUE TITLE
Scroll event on file list

### ISSUE THREAD

**Issue by alexisdurieux** [TimboKZ/Chonky#69]
Hello, 

Would it be possible to listen to the end of the files list scroll in order to imlement lazy loading.
Right now I am trying to listen to the scroll events on `.chonky-fileListWrapper` but I am still making it work. 

How would you think the best way to do it would be in the short term ? In the long term, does it make sense to expose an `onScroll` props ? 

Thanks !

**Comment by TimboKZ** [comment]
Hey @alexisdurieux, I think the approach you suggested makes sense in the short-term. I think exposing `onScroll` is a great idea, I'll try to fit them into one of the feature releases.

**Comment by alexisdurieux** [comment]
Thanks @TimboKZ . I can try to open a PR about if you want :)

**Comment by TimboKZ** [comment]
Sounds good, go for it!

**Comment by alexisdurieux** [comment]
#72

**Comment by alexisdurieux** [comment]
I am closing this since you merge #72.
Thanks !

**Comment by maidangzhu** [comment]
OnScroll on FileList can't even dispatch
