### ISSUE TITLE
Depth of presentation layer

### ISSUE THREAD

**Issue by Steve9400** [TimboKZ/Chonky#75]
Your intro states _Chonky takes a list of files and shows them to the user.  It does not and should not know where the files come from or how file operations are executed._ 

Could you please clarify:  Does the presentation layer only know of the files currently displayed in the view?  That is, is it correct that Chonky cannot take an entire file tree, (i.e., via `files`), and automatically manage the view when a user navigates up and down thru a tree?

I'm guessing that my code will need to manage navigation to different folders, and that the Chonky code will make calls out whenever the user navigates around.  And then my code will need to decide what files and folders to display in that newly selected view, then pass those to Chonky by populating `files` appropriately.  Is that correct?

**Comment by TimboKZ** [comment]
Hi @Steve9400, that is correct.

**Comment by Steve9400** [comment]
Thanks for the prompt response!
