### ISSUE TITLE
Displaying time (in addition to date) of file timestamps

### ISSUE THREAD

**Issue by Steve9400** [TimboKZ/Chonky#76]
I built up a demo and provided timestamps to the files, but I only see the dates displayed in the view and not the times.  Is there a configuration to enable time display (along with date)?

**Comment by TimboKZ** [comment]
Hi, you can use a custom date formatter to display the time, check out this demo:

https://chonky.io/storybook/2.x/?path=/story/file-browser-demos--localization

**Comment by Steve9400** [comment]
Thanks, Tim.
