### ISSUE TITLE
Trouble Getting Drag and Drop to function

### ISSUE THREAD

**Issue by mexicantexan** [TimboKZ/Chonky#78]
I'm having trouble getting the Drag and Drop feature to function in my React App. I have "react-dnd": "11.1.3", "react-dnd-html5-backend": "11.1.3", "chonky": "2.1.0", "chonky-icon-fontawesome": "2.1.0", and "react": 16.13.1 installed in the application (amongst other libraries, but these seemed pertinent to this issue). Here is my code for the component:

`export const LeFileBrowser = () => {
    
    const files = [
        { id: 'lht', name: 'Personal Drive', isDir: true, draggable: true, droppable: true, openable: true },
        { id: 'lhu', name: 'Company Drive', isDir: true, draggable: true, droppable: true, openable: true },
        {
            id: 'mcd',
            name: 'chonky-sphere-v2.png',
            thumbnailUrl: 'https://chonky.io/chonky-sphere-v2.png',
            isDir: false,
            draggable: true,
        },
    ];
    const folderChain = [
        { id: 'xcv', name: 'X-Drive', isDir: true },
    ];
    const fileBrowserRef = React.useRef(FileBrowserHandle);
    const invertSelection = React.useCallback(() => {
        if (!fileBrowserRef.current) return
        const oldSelection = fileBrowserRef.current.getFileSelection()
        const newSelection = new Set()
        for (const file of files) {
          if (!oldSelection.has(file.id)) newSelection.add(file.id)
        }
        fileBrowserRef.current.setFileSelection(newSelection)
      }, [files])
    const whatsBeingCalled = React.useCallback((ref) =>{
        console.log('ref', ref)
    })
    return (
        <div style={{ height: 300 }}>
            <button className="demo-button" onClick={invertSelection}>
                Invert selection
              </button>
                <FileBrowser
                    files={files}
                    folderChain={folderChain}
                    ref={fileBrowserRef}
                    disableDragAndDrop={false}
                    disableDragAndDropProvider={false}
                    darkMode={true}
                    onFileAction={whatsBeingCalled}
                >
                    <FileNavbar />
                    <FileToolbar />
                    <FileList />
                    <FileContextMenu />
                </FileBrowser>
        </div>
    );
};`

I should also note that I am calling:
 `setChonkyDefaults({
    iconComponent: ChonkyIconFA,
});`
at a higher level within the application.

I've tried using the `<FullFileBrowser files={files} folderChain={folderChain}/>` as well.
I've tried wrapping the App in the react-dnd-html5-backend tag like so `<DndProvider backend={HTML5Backend}>
                <App/>
            </DndProvider>`
Along with just wrapping the component itself.

I'm probably missing something obvious  :/ but can't seem to find it at the moment.

**Comment by embeddedt** [comment]
Bump. I'm trying to upgrade my app from Chonky v1 to v2 (partially because of drag-and-drop) and I'm having the same problem.

**Comment by embeddedt** [comment]
Well; I'm now trying to isolate the problem because I need drag-and-drop support for my application.

I started by trying to reproduce your problem in a sandbox, but interestingly, it [works fine there](https://codesandbox.io/s/chonky-drag-test-gck4q).

EDIT: Figured something else out; it breaks if I add a custom `DndProvider` and set `disableDragAndDropProvider` to true.

EDIT2: Even without a custom provider actually being used, the mere presence of my own `react-dnd` import seems to break it.

**Comment by embeddedt** [comment]
For everyone watching this issue, I have found that the issue seems to be caused by a newer version of `react-dnd` being installed in your project than what Chonky is expecting.

If you use `react-dnd@11.1.3` and `react-dnd-html5-backend@11.1.3`, the issue seems to go away.

**Comment by mexicantexan** [comment]
@embeddedt it's weird because that is what I'm using. Great sleuthing though!

**Comment by embeddedt** [comment]
I wonder if your bundler is bundling two separate copies of `react-dnd`? That might cause the same type of issue.

**Comment by mexicantexan** [comment]
I'll have to check when I get back home to my computer... honestly, that hadn't even crossed my mind but you're most likely onto something. I'll update asap

**Comment by TimboKZ** [comment]
Hey @mexicantexan @embeddedt, I believe this is indeed related to multiple and/or incorrect versions of `react-dnd` installed. `yarn list --pattern react-dnd`/`npm ls react-dnd` should show the versions used.
