### ISSUE TITLE
Chonky uses Path in Browser

### ISSUE THREAD

**Issue by dragosrotaru** [TimboKZ/Chonky#80]
Looks like Chonky is importing path, a NodeJS-only package to use the function path.extname(). This expects `process` to be in scope, but the `process` global is only available in NodeJS. Some configurations of webpack (like the default one for Create React App) will allow this to work, probably by substituting the value for process.platform at build time, but this shouldn't be necessary.

path NPM repo: https://www.npmjs.com/package/path

At your request, I will submit a PR to fix this.

**Comment by taotau** [comment]
Im trying to use Chonky in a non create-react-app environment, and am bumping into the same issue.

Would you mind sharing your PR or some pointers on what needs to be tweaked in webpack.config please ?

**Comment by taotau** [comment]
If anyone is interested, my workaround for the problem was to include the path-browserify package in my project.

This is loaded in webpack using 
```

resolve: {
    fallback : { 
      "path": require.resolve("path-browserify") 
    }
  }
```

**Comment by TimboKZ** [comment]
Thanks for catching this, that was an unfortunate oversight. It was fixed in https://github.com/TimboKZ/Chonky/commit/2815dda30eae17b553502b3f6ce602626d1633e7#diff-8245d43ead1e93c4574e4151e78c34bfeceb3796ff2662d726eab57f875c3c92L1 and will be included in the next release.
