### ISSUE TITLE
File Context Menu

### ISSUE THREAD

**Issue by chiejhay** [TimboKZ/Chonky#81]
Everytime i right click, the file context menu open everywhere not on the mouse pointer where i clicked it. is there a way to customize the style? thank you.. Your library is pretty much amazing..

**Comment by TimboKZ** [comment]
Hi, I'm not quite sure what you mean by context menu opening "everywhere". Can you provide some images/gif/code examples to explain the problem?

Closing this issue as there is not enough info to debug this problem, feel free to reopen when you have more details.
