### ISSUE TITLE
Disable creating folder on 2nd level folders?

### ISSUE THREAD

**Issue by niikkiin** [TimboKZ/Chonky#89]
Hi, first of all thank you for this great library, it is very useful, just want to know if is it possible to disable creating folder on lower level folders? TIA.

**Comment by TimboKZ** [comment]
Hey @niikkiin, yes it's possible by doing something like:
```jsx
<FullFileBrowser
    files={files}
    folderChain={folderChain}
    fileActions={folderChain.length > 1 ? null : [ ChonkyActions.CreateFolder ]}
/>
```
