### ISSUE TITLE
Custom Folder CARD

### ISSUE THREAD

**Issue by medaminesmart** [TimboKZ/Chonky#96]
Hi,

Is there anyway to personalize the used folder card, i would like to add some stats (5 per card) and controled

![Capture](https://user-images.githubusercontent.com/86656400/123772940-8ae31d00-d8cc-11eb-9e17-6308db2ca90b.JPG)

Thanks

**Comment by TimboKZ** [comment]
You can try to hack something using a custom icon component as shown in https://chonky.io/docs/2.x/basics/icons.
