### ISSUE TITLE
`onFileAction`'s `ChonkyActions`'s payload is of type 'unknown'

### ISSUE THREAD

**Issue by Robbie-Cook** [TimboKZ/Chonky#99]
Hey, just want to say I love Chonky!

When I get a `payload` from a ChonkyActions, it seems to be of type `unknown`. Not a biggie, and I can see you have done some great typing in this package. Could we maybe get some more intelligent payload data (e.g. file name if file, etc.)?

Have a good one,
Robbie

**Comment by TimboKZ** [comment]
Hi, this is a known problem and I had mixed results getting this to work in different editors. The "recipe" that worked for me in the end is the one shown on https://chonky.io/docs/2.x/file-actions/action-handler#type-safe-action-handler:
![image](https://user-images.githubusercontent.com/5504588/148660759-bde62cb8-4081-41e0-8fd9-a19001e33165.png)

Note how the if clause checks for `data.id === ...` and not `data.action.id === ...`. From my experience, using the latter does not narrow down the type of `data` enough for IntelliSense to figure out the `data.payload` type, so the check has to be explicitly against `data.id`.

Closing this issue as this is all the insight I can provide at the moment, feel free to reopen if you have more questions.
